export const ENTRY_CREATE_REQUEST = "ENTRY_CREATE_REQUEST";
export const ENTRY_CREATE_SUCESS = "ENTRY_CREATE_SUCESS";
export const ENTRY_CREATE_FAIL = "ENTRY_CREATE_FAIL";
export const ENTRY_CREATE_RESET = "ENTRY_CREATE_RESET";

export const ENTRY_LIST_MY_REQUEST = "ENTRY_LIST_MY_REQUEST";
export const ENTRY_LIST_MY_SUCESS = "ENTRY_LIST_MY_SUCESS";
export const ENTRY_LIST_MY_FAIL = "ENTRY_LIST_MY_FAIL";
export const ENTRY_LIST_MY_RESET = "ENTRY_LIST_MY_RESET";
