export const ENTRY_TEMPLATE_CREATE_REQUEST = "ENTRY_TEMPLATE_CREATE_REQUEST";
export const ENTRY_TEMPLATE_CREATE_SUCESS = "ENTRY_TEMPLATE_CREATE_SUCESS";
export const ENTRY_TEMPLATE_CREATE_FAIL = "ENTRY_TEMPLATE_CREATE_FAIL";
export const ENTRY_TEMPLATE_CREATE_RESET = "ENTRY_TEMPLATE_CREATE_RESET";

export const ENTRY_TEMPLATE_LIST_MY_REQUEST = "ENTRY_TEMPLATE_LIST_MY_REQUEST";
export const ENTRY_TEMPLATE_LIST_MY_SUCESS = "ENTRY_TEMPLATE_LIST_MY_SUCESS";
export const ENTRY_TEMPLATE_LIST_MY_FAIL = "ENTRY_TEMPLATE_LIST_MY_FAIL";
export const ENTRY_TEMPLATE_LIST_MY_RESET = "ENTRY_TEMPLATE_LIST_MY_RESET";
