export const ORG_CREATE_REQUEST = "ORG_CREATE_REQUEST";
export const ORG_CREATE_SUCESS = "ORG_CREATE_SUCESS";
export const ORG_CREATE_FAIL = "ORG_CREATE_FAIL";
export const ORG_CREATE_RESET = "ORG_CREATE_RESET";

export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCESS = "PROJECT_DETAILS_SUCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

export const ORG_LIST_MY_REQUEST = "ORG_LIST_MY_REQUEST";
export const ORG_LIST_MY_SUCESS = "ORG_LIST_MY_SUCESS";
export const ORG_LIST_MY_FAIL = "ORG_LIST_MY_FAIL";
export const ORG_LIST_MY_RESET = "ORG_LIST_MY_RESET";

export const PROJECT_CREATE_COLLAB_REQUEST = "PROJECT_CREATE_COLLAB_REQUEST";
export const PROJECT_CREATE_COLLAB_SUCESS = "PROJECT_CREATE_COLLAB_SUCESS";
export const PROJECT_CREATE_COLLAB_FAIL = "PROJECT_CREATE_COLLAB_FAIL";
export const PROJECT_CREATE_COLLAB_RESET = "PROJECT_CREATE_COLLAB_RESET";

export const ORG_GET_COLLAB_REQUEST = "ORG_GET_COLLAB_REQUEST";
export const ORG_GET_COLLAB_SUCESS = "ORG_GET_COLLAB_SUCESS";
export const ORG_GET_COLLAB_FAIL = "ORG_GET_COLLAB_FAIL";
export const ORG_GET_COLLAB_RESET = "ORG_GET_COLLAB_RESET";

export const PROJECT_UPDATE_COLLAB_REQUEST = "PROJECT_UPDATE_COLLAB_REQUEST";
export const PROJECT_UPDATE_COLLAB_SUCESS = "PROJECT_UPDATE_COLLAB_SUCESS";
export const PROJECT_UPDATE_COLLAB_FAIL = "PROJECT_UPDATE_COLLAB_FAIL";
export const PROJECT_UPDATE_COLLAB_RESET = "PROJECT_UPDATE_COLLAB_RESET";

export const PROJECT_UPDATE_PROFILE_REQUEST = "PROJECT_UPDATE_PROFILE_REQUEST";
export const PROJECT_UPDATE_PROFILE_SUCESS = "PROJECT_UPDATE_PROFILE_SUCESS";
export const PROJECT_UPDATE_PROFILE_FAIL = "PROJECT_UPDATE_PROFILE_FAIL";
export const PROJECT_UPDATE_PROFILE_RESET = "PROJECT_UPDATE_PROFILE_RESET";
