export const PROTOCOL_CREATE_REQUEST = "PROTOCOL_CREATE_REQUEST";
export const PROTOCOL_CREATE_SUCESS = "PROTOCOL_CREATE_SUCESS";
export const PROTOCOL_CREATE_FAIL = "PROTOCOL_CREATE_FAIL";
export const PROTOCOL_CREATE_RESET = "PROTOCOL_CREATE_RESET";

export const PROTOCOL_LIST_MY_REQUEST = "PROTOCOL_LIST_MY_REQUEST";
export const PROTOCOL_LIST_MY_SUCESS = "PROTOCOL_LIST_MY_SUCESS";
export const PROTOCOL_LIST_MY_FAIL = "PROTOCOL_LIST_MY_FAIL";
export const PROTOCOL_LIST_MY_RESET = "PROTOCOL_LIST_MY_RESET";
