export const SAMPLE_CREATE_REQUEST = "SAMPLE_CREATE_REQUEST";
export const SAMPLE_CREATE_SUCESS = "SAMPLE_CREATE_SUCESS";
export const SAMPLE_CREATE_FAIL = "SAMPLE_CREATE_FAIL";
export const SAMPLE_CREATE_RESET = "SAMPLE_CREATE_RESET";

export const SAMPLE_LIST_MY_REQUEST = "SAMPLE_LIST_MY_REQUEST";
export const SAMPLE_LIST_MY_SUCESS = "SAMPLE_LIST_MY_SUCESS";
export const SAMPLE_LIST_MY_FAIL = "SAMPLE_LIST_MY_FAIL";
export const SAMPLE_LIST_MY_RESET = "SAMPLE_LIST_MY_RESET";
