export const SOP_CREATE_REQUEST = "SOP_CREATE_REQUEST";
export const SOP_CREATE_SUCESS = "SOP_CREATE_SUCESS";
export const SOP_CREATE_FAIL = "SOP_CREATE_FAIL";
export const SOP_CREATE_RESET = "SOP_CREATE_RESET";

export const SOP_LIST_MY_REQUEST = "SOP_LIST_MY_REQUEST";
export const SOP_LIST_MY_SUCESS = "SOP_LIST_MY_SUCESS";
export const SOP_LIST_MY_FAIL = "SOP_LIST_MY_FAIL";
export const SOP_LIST_MY_RESET = "SOP_LIST_MY_RESET";
