export const TASK_CREATE_REQUEST = "TASK_CREATE_REQUEST";
export const TASK_CREATE_SUCESS = "TASK_CREATE_SUCESS";
export const TASK_CREATE_FAIL = "TASK_CREATE_FAIL";
export const TASK_CREATE_RESET = "TASK_CREATE_RESET";

export const TASK_LIST_MY_REQUEST = "TASK_LIST_MY_REQUEST";
export const TASK_LIST_MY_SUCESS = "TASK_LIST_MY_SUCESS";
export const TASK_LIST_MY_FAIL = "TASK_LIST_MY_FAIL";
export const TASK_LIST_MY_RESET = "TASK_LIST_MY_RESET";

export const TASK_LIST_MY_PERSONAL_REQUEST = "TASK_LIST_MY_PERSONAL_REQUEST";
export const TASK_LIST_MY_PERSONAL_SUCESS = "TASK_LIST_MY_PERSONAL_SUCESS";
export const TASK_LIST_MY_PERSONAL_FAIL = "TASK_LIST_MY_PERSONAL_FAIL";
export const TASK_LIST_MY_PERSONAL_RESET = "TASK_LIST_MY_PERSONAL_RESET";

export const TASK_GET_COLLAB_REQUEST = "TASK_GET_COLLAB_REQUEST";
export const TASK_GET_COLLAB_SUCESS = "TASK_GET_COLLAB_SUCESS";
export const TASK_GET_COLLAB_FAIL = "TASK_GET_COLLAB_FAIL";
export const TASK_GET_COLLAB_RESET = "TASK_GET_COLLAB_RESET";

export const TASK_UPDATE_PROFILE_REQUEST = "TASK_UPDATE_PROFILE_REQUEST";
export const TASK_UPDATE_PROFILE_SUCESS = "TASK_UPDATE_PROFILE_SUCESS";
export const TASK_UPDATE_PROFILE_FAIL = "TASK_UPDATE_PROFILE_FAIL";
export const TASK_UPDATE_PROFILE_RESET = "TASK_UPDATE_PROFILE_RESET";
